package com.piaohai.mis.model;

import java.util.Date;

public class AttaRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTA_RELATION.ATRE_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String atreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTA_RELATION.ATRE_ATTA_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String atreAttaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTA_RELATION.ATRE_RELATION_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String atreRelationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTA_RELATION.ATRE_TYPE
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String atreType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTA_RELATION.DATE_CREATED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTA_RELATION.DATE_MODIFIED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private Date dateModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTA_RELATION.CREATER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTA_RELATION.MODIFIER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTA_RELATION.ATRE_ID
     *
     * @return the value of ATTA_RELATION.ATRE_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getAtreId() {
        return atreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTA_RELATION.ATRE_ID
     *
     * @param atreId the value for ATTA_RELATION.ATRE_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAtreId(String atreId) {
        this.atreId = atreId == null ? null : atreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTA_RELATION.ATRE_ATTA_ID
     *
     * @return the value of ATTA_RELATION.ATRE_ATTA_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getAtreAttaId() {
        return atreAttaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTA_RELATION.ATRE_ATTA_ID
     *
     * @param atreAttaId the value for ATTA_RELATION.ATRE_ATTA_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAtreAttaId(String atreAttaId) {
        this.atreAttaId = atreAttaId == null ? null : atreAttaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTA_RELATION.ATRE_RELATION_ID
     *
     * @return the value of ATTA_RELATION.ATRE_RELATION_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getAtreRelationId() {
        return atreRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTA_RELATION.ATRE_RELATION_ID
     *
     * @param atreRelationId the value for ATTA_RELATION.ATRE_RELATION_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAtreRelationId(String atreRelationId) {
        this.atreRelationId = atreRelationId == null ? null : atreRelationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTA_RELATION.ATRE_TYPE
     *
     * @return the value of ATTA_RELATION.ATRE_TYPE
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getAtreType() {
        return atreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTA_RELATION.ATRE_TYPE
     *
     * @param atreType the value for ATTA_RELATION.ATRE_TYPE
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAtreType(String atreType) {
        this.atreType = atreType == null ? null : atreType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTA_RELATION.DATE_CREATED
     *
     * @return the value of ATTA_RELATION.DATE_CREATED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTA_RELATION.DATE_CREATED
     *
     * @param dateCreated the value for ATTA_RELATION.DATE_CREATED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTA_RELATION.DATE_MODIFIED
     *
     * @return the value of ATTA_RELATION.DATE_MODIFIED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public Date getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTA_RELATION.DATE_MODIFIED
     *
     * @param dateModified the value for ATTA_RELATION.DATE_MODIFIED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTA_RELATION.CREATER
     *
     * @return the value of ATTA_RELATION.CREATER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTA_RELATION.CREATER
     *
     * @param creater the value for ATTA_RELATION.CREATER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTA_RELATION.MODIFIER
     *
     * @return the value of ATTA_RELATION.MODIFIER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTA_RELATION.MODIFIER
     *
     * @param modifier the value for ATTA_RELATION.MODIFIER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
}