package com.piaohai.mis.model;

import java.util.Date;

public class Attachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.ATTA_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String attaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.ATTA_NAME
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String attaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.ATTA_SIZE
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private Long attaSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.ATTA_TYPE
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String attaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.ATTA_LOCATION
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String attaLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.ATTA_PS
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String attaPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.DATE_CREATED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.DATE_MODIFIED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private Date dateModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.CREATER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.MODIFIER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.ATTA_ID
     *
     * @return the value of ATTACHMENT.ATTA_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getAttaId() {
        return attaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.ATTA_ID
     *
     * @param attaId the value for ATTACHMENT.ATTA_ID
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAttaId(String attaId) {
        this.attaId = attaId == null ? null : attaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.ATTA_NAME
     *
     * @return the value of ATTACHMENT.ATTA_NAME
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getAttaName() {
        return attaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.ATTA_NAME
     *
     * @param attaName the value for ATTACHMENT.ATTA_NAME
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAttaName(String attaName) {
        this.attaName = attaName == null ? null : attaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.ATTA_SIZE
     *
     * @return the value of ATTACHMENT.ATTA_SIZE
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public Long getAttaSize() {
        return attaSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.ATTA_SIZE
     *
     * @param attaSize the value for ATTACHMENT.ATTA_SIZE
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAttaSize(Long attaSize) {
        this.attaSize = attaSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.ATTA_TYPE
     *
     * @return the value of ATTACHMENT.ATTA_TYPE
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getAttaType() {
        return attaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.ATTA_TYPE
     *
     * @param attaType the value for ATTACHMENT.ATTA_TYPE
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAttaType(String attaType) {
        this.attaType = attaType == null ? null : attaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.ATTA_LOCATION
     *
     * @return the value of ATTACHMENT.ATTA_LOCATION
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getAttaLocation() {
        return attaLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.ATTA_LOCATION
     *
     * @param attaLocation the value for ATTACHMENT.ATTA_LOCATION
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAttaLocation(String attaLocation) {
        this.attaLocation = attaLocation == null ? null : attaLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.ATTA_PS
     *
     * @return the value of ATTACHMENT.ATTA_PS
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getAttaPs() {
        return attaPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.ATTA_PS
     *
     * @param attaPs the value for ATTACHMENT.ATTA_PS
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setAttaPs(String attaPs) {
        this.attaPs = attaPs == null ? null : attaPs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.DATE_CREATED
     *
     * @return the value of ATTACHMENT.DATE_CREATED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.DATE_CREATED
     *
     * @param dateCreated the value for ATTACHMENT.DATE_CREATED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.DATE_MODIFIED
     *
     * @return the value of ATTACHMENT.DATE_MODIFIED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public Date getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.DATE_MODIFIED
     *
     * @param dateModified the value for ATTACHMENT.DATE_MODIFIED
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.CREATER
     *
     * @return the value of ATTACHMENT.CREATER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.CREATER
     *
     * @param creater the value for ATTACHMENT.CREATER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.MODIFIER
     *
     * @return the value of ATTACHMENT.MODIFIER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.MODIFIER
     *
     * @param modifier the value for ATTACHMENT.MODIFIER
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
}