package com.piaohai.mis.model;

import java.util.Date;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.CHAN_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String chanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.CHAN_NAME
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String chanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.CHAN_SEQ
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private Integer chanSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.CHAN_STATUS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String chanStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.CHAN_PARENT_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String chanParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.CHAN_PS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String chanPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.DATE_CREATED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.DATE_MODIFIED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private Date dateModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.CREATER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.MODIFIER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String modifier;
    //类型:0(枝干)、1(叶子)
    private String chanType;
    //列表页面
    private String chanListPage;
    //明细预览页面
    private String chanDetailPage;

    public String getChanListPage() {
		return chanListPage;
	}

	public void setChanListPage(String chanListPage) {
		this.chanListPage = chanListPage;
	}

	public String getChanDetailPage() {
		return chanDetailPage;
	}

	public void setChanDetailPage(String chanDetailPage) {
		this.chanDetailPage = chanDetailPage;
	}

	public String getChanType() {
		return chanType;
	}

	public void setChanType(String chanType) {
		this.chanType = chanType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.CHAN_ID
     *
     * @return the value of CHANNEL.CHAN_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getChanId() {
        return chanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.CHAN_ID
     *
     * @param chanId the value for CHANNEL.CHAN_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setChanId(String chanId) {
        this.chanId = chanId == null ? null : chanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.CHAN_NAME
     *
     * @return the value of CHANNEL.CHAN_NAME
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getChanName() {
        return chanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.CHAN_NAME
     *
     * @param chanName the value for CHANNEL.CHAN_NAME
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setChanName(String chanName) {
        this.chanName = chanName == null ? null : chanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.CHAN_SEQ
     *
     * @return the value of CHANNEL.CHAN_SEQ
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public Integer getChanSeq() {
        return chanSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.CHAN_SEQ
     *
     * @param chanSeq the value for CHANNEL.CHAN_SEQ
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setChanSeq(Integer chanSeq) {
        this.chanSeq = chanSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.CHAN_STATUS
     *
     * @return the value of CHANNEL.CHAN_STATUS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getChanStatus() {
        return chanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.CHAN_STATUS
     *
     * @param chanStatus the value for CHANNEL.CHAN_STATUS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setChanStatus(String chanStatus) {
        this.chanStatus = chanStatus == null ? null : chanStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.CHAN_PARENT_ID
     *
     * @return the value of CHANNEL.CHAN_PARENT_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getChanParentId() {
        return chanParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.CHAN_PARENT_ID
     *
     * @param chanParentId the value for CHANNEL.CHAN_PARENT_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setChanParentId(String chanParentId) {
        this.chanParentId = chanParentId == null ? null : chanParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.CHAN_PS
     *
     * @return the value of CHANNEL.CHAN_PS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getChanPs() {
        return chanPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.CHAN_PS
     *
     * @param chanPs the value for CHANNEL.CHAN_PS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setChanPs(String chanPs) {
        this.chanPs = chanPs == null ? null : chanPs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.DATE_CREATED
     *
     * @return the value of CHANNEL.DATE_CREATED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.DATE_CREATED
     *
     * @param dateCreated the value for CHANNEL.DATE_CREATED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.DATE_MODIFIED
     *
     * @return the value of CHANNEL.DATE_MODIFIED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public Date getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.DATE_MODIFIED
     *
     * @param dateModified the value for CHANNEL.DATE_MODIFIED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.CREATER
     *
     * @return the value of CHANNEL.CREATER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.CREATER
     *
     * @param creater the value for CHANNEL.CREATER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.MODIFIER
     *
     * @return the value of CHANNEL.MODIFIER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.MODIFIER
     *
     * @param modifier the value for CHANNEL.MODIFIER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
    
}