package com.piaohai.mis.model;

import java.util.Date;
import java.util.List;

public class Document {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.DOC_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String docId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.DOC_TITLE
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String docTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.DOC_CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String docChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.DOC_STATUS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String docStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.DOC_ATTACH
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String docAttach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.DOC_PS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String docPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.DATE_CREATED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.DATE_MODIFIED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private Date dateModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.CREATER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.MODIFIER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENT.DOC_CONTENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String docContent;
    /**
     * 附件
     */
    private List<Attachment> attachments;
    /**
     * 明细界面
     */
    private String docDetailPage;
    
    

	public String getDocDetailPage() {
		return docDetailPage;
	}

	public void setDocDetailPage(String docDetailPage) {
		this.docDetailPage = docDetailPage;
	}

	public List<Attachment> getAttachments() {
		return attachments;
	}

	public void setAttachments(List<Attachment> attachments) {
		this.attachments = attachments;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.DOC_ID
     *
     * @return the value of DOCUMENT.DOC_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.DOC_ID
     *
     * @param docId the value for DOCUMENT.DOC_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDocId(String docId) {
        this.docId = docId == null ? null : docId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.DOC_TITLE
     *
     * @return the value of DOCUMENT.DOC_TITLE
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getDocTitle() {
        return docTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.DOC_TITLE
     *
     * @param docTitle the value for DOCUMENT.DOC_TITLE
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDocTitle(String docTitle) {
        this.docTitle = docTitle == null ? null : docTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.DOC_CHANNEL
     *
     * @return the value of DOCUMENT.DOC_CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getDocChannel() {
        return docChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.DOC_CHANNEL
     *
     * @param docChannel the value for DOCUMENT.DOC_CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDocChannel(String docChannel) {
        this.docChannel = docChannel == null ? null : docChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.DOC_STATUS
     *
     * @return the value of DOCUMENT.DOC_STATUS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getDocStatus() {
        return docStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.DOC_STATUS
     *
     * @param docStatus the value for DOCUMENT.DOC_STATUS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDocStatus(String docStatus) {
        this.docStatus = docStatus == null ? null : docStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.DOC_ATTACH
     *
     * @return the value of DOCUMENT.DOC_ATTACH
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getDocAttach() {
        return docAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.DOC_ATTACH
     *
     * @param docAttach the value for DOCUMENT.DOC_ATTACH
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDocAttach(String docAttach) {
        this.docAttach = docAttach == null ? null : docAttach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.DOC_PS
     *
     * @return the value of DOCUMENT.DOC_PS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getDocPs() {
        return docPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.DOC_PS
     *
     * @param docPs the value for DOCUMENT.DOC_PS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDocPs(String docPs) {
        this.docPs = docPs == null ? null : docPs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.DATE_CREATED
     *
     * @return the value of DOCUMENT.DATE_CREATED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.DATE_CREATED
     *
     * @param dateCreated the value for DOCUMENT.DATE_CREATED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.DATE_MODIFIED
     *
     * @return the value of DOCUMENT.DATE_MODIFIED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public Date getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.DATE_MODIFIED
     *
     * @param dateModified the value for DOCUMENT.DATE_MODIFIED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.CREATER
     *
     * @return the value of DOCUMENT.CREATER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.CREATER
     *
     * @param creater the value for DOCUMENT.CREATER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.MODIFIER
     *
     * @return the value of DOCUMENT.MODIFIER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.MODIFIER
     *
     * @param modifier the value for DOCUMENT.MODIFIER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENT.DOC_CONTENT
     *
     * @return the value of DOCUMENT.DOC_CONTENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getDocContent() {
        return docContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENT.DOC_CONTENT
     *
     * @param docContent the value for DOCUMENT.DOC_CONTENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDocContent(String docContent) {
        this.docContent = docContent == null ? null : docContent.trim();
    }
}