package com.piaohai.mis.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USER_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USER_NAME
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USER_PASSWORD
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USER_STATUS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USER_PS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String userPs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.DATE_CREATED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.DATE_MODIFIED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private Date dateModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.CREATER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.MODIFIER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USER_ID
     *
     * @return the value of USER_INFO.USER_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USER_ID
     *
     * @param userId the value for USER_INFO.USER_ID
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USER_NAME
     *
     * @return the value of USER_INFO.USER_NAME
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USER_NAME
     *
     * @param userName the value for USER_INFO.USER_NAME
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USER_PASSWORD
     *
     * @return the value of USER_INFO.USER_PASSWORD
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USER_PASSWORD
     *
     * @param userPassword the value for USER_INFO.USER_PASSWORD
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USER_STATUS
     *
     * @return the value of USER_INFO.USER_STATUS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USER_STATUS
     *
     * @param userStatus the value for USER_INFO.USER_STATUS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USER_PS
     *
     * @return the value of USER_INFO.USER_PS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getUserPs() {
        return userPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USER_PS
     *
     * @param userPs the value for USER_INFO.USER_PS
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setUserPs(String userPs) {
        this.userPs = userPs == null ? null : userPs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.DATE_CREATED
     *
     * @return the value of USER_INFO.DATE_CREATED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.DATE_CREATED
     *
     * @param dateCreated the value for USER_INFO.DATE_CREATED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.DATE_MODIFIED
     *
     * @return the value of USER_INFO.DATE_MODIFIED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public Date getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.DATE_MODIFIED
     *
     * @param dateModified the value for USER_INFO.DATE_MODIFIED
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.CREATER
     *
     * @return the value of USER_INFO.CREATER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.CREATER
     *
     * @param creater the value for USER_INFO.CREATER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.MODIFIER
     *
     * @return the value of USER_INFO.MODIFIER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.MODIFIER
     *
     * @param modifier the value for USER_INFO.MODIFIER
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
}