package com.piaohai.mis.dao;

import com.piaohai.mis.model.Attachment;

public interface AttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    int deleteByPrimaryKey(String attaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    Attachment selectByPrimaryKey(String attaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    int updateByPrimaryKeySelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Wed Sep 25 15:09:33 CST 2013
     */
    int updateByPrimaryKey(Attachment record);
}