package com.piaohai.mis.dao;

import java.util.List;

import com.piaohai.mis.model.Channel;

public interface ChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int deleteByPrimaryKey(String chanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int insertSelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    Channel selectByPrimaryKey(String chanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int updateByPrimaryKeySelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int updateByPrimaryKey(Channel record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    List<Channel> selectByParentId(String chanParentId);
    List<Channel>  selectRoot();
    List<Channel>  getAll();
    
}