package com.piaohai.mis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.piaohai.mis.common.page.Page;
import com.piaohai.mis.model.Document;

public interface DocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int deleteByPrimaryKey(String docId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int insert(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int insertSelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    Document selectByPrimaryKey(String docId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int updateByPrimaryKeySelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENT
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int updateByPrimaryKey(Document record);
    List<Document> selectByChannelId(String chanId);
    Document getDocDetail(String docId);
    /**
     * 分页：根据频道ID查询
     * @param chanId
     * @return
     */
    List<Document> docListPage(@Param("page") Page page,@Param("chanId") String  chanId);
    
    /**
     * 分页：根据频道ID查询
     * @param chanId
     * @return
     */
    List<Document> docListPageByChannel(@Param("page") Page page,@Param("docChannel") String  docChannel);
    
}