package com.piaohai.mis.dao;

import com.piaohai.mis.model.UserInfo;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    UserInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbggenerated Tue Sep 17 13:54:42 CST 2013
     */
    int updateByPrimaryKey(UserInfo record);
    
    UserInfo selectByUserName(String userName);
    
}